### ISSUE TITLE
Error on CentOS 7

### ISSUE THREAD

**Issue by joejordanbrown** [tripflex/cpsetup#11]
-----------------------------------------------------------------
- Securing the server with configuration tweaks, please wait... -
-----------------------------------------------------------------
Redirecting to /bin/systemctl stop  portreserve.service
Failed to stop portreserve.service: Unit portreserve.service not loaded.
error reading information on service portreserve: No such file or directory
cPanel Apache Local Configuration file ( /var/cpanel/conf/apache/local ) already exists, unable to update
./cpsetup: line 534: /etc/init.d/sshd: No such file or directory
Profile limits installed

CentOS 7

**Comment by tripflex** [comment]
The first couple lines can probably be ignored, that's related to the call to stop `portreserve` and disable it.   Could probably do some checks to see if it's installed before running that command, but may end up being more work than necessary.

The error about apache local configuration file is because we don't want to duplicate adding code to end of that file for server signature, tokens, and traceenable ... this technically shouldn't already exist, if it does, chances are you already ran this script or have already configured those settings.

The sshd no such file or directory however is a bug, should be calling systemctl or service instead of trying to call /etc/init.d/sshd directly
